apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ml-api
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 1000
      containers:
      - name: ml-api
        image: us-central1-docker.pkg.dev/cool-clarity-437320-d0/keras-repo/ml-api:latest
        ports:
        - name: http1
          containerPort: 8000
        resources:
          limits:
            cpu: "2"
            memory: "1Gi"
        startupProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 0
          timeoutSeconds: 10
          periodSeconds: 60
          failureThreshold: 10